//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseReader.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        DateHelper dateHelper = new DateHelper();
        public string timeStamp { get; set; }
        public int CaloriesBurnt { get; set; }
        public string Id { get; set; }
        public DateTime DateTime
        {
            get
            {
                DateTime date = new DateTime();
                DateTime.TryParse(timeStamp, out date);
                return date;
            }
        }

        public string Time
        {
            get { return DateTime.ToString("HH:mm"); }
        }

        public bool IsSameDate(DateTime date) => dateHelper.IsSameDate(DateTime, date);
        public bool IsSameTimeInMins(DateTime date) => dateHelper.IsSameTime(DateTime, date);

        public double CaloriesBurntPerMin = 0;        

    }
}
