//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseReader.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class UserSetting
    {
        public int Id { get; set; }
        public string Name { get; set; }
        [Display(Name="Typical Daily Calories Burnt")]
        public int TypicalCaloriesBurnt { get; set; }
    }
}
